---
- name: make sure unwanted packages are absent
  become: True
  package:
    pkg:
      - ntp
      - openntpd
    state: absent

- name: install tools
  become: True
  package:
    name: "{{item}}"
    state: present
  with_items:
    - dbus

- name: check for localtime symlink
  stat:
    path: /etc/localtime
  register: localtime

- name: remove /etc/localtime if it isn't a symlink
  become: True
  file: 
    path: /etc/localtime
    state: absent
  when: localtime.stat.islnk is defined and localtime.stat.islnk == False

- name: set /etc/localtime symlink
  become: True
  file: 
    path: /etc/localtime
    src: /usr/share/zoneinfo/{{ timezone_area }}/{{ timezone }} 
    state: link
  when: (localtime.stat.islnk is defined and localtime.stat.islnk == False) or localtime.stat.exists == False

- block:
  - name: install timesyncd configuration
    become: True
    template:
      src: etc_systemd_timesyncd.conf.j2
      dest: /etc/systemd/timesyncd.conf
      owner: root
      group: root
      mode: 0644
    notify:
      - restart timesyncd

  - name: enable timesyncd
    become: True
    service:
      name: systemd-timesyncd.service
      enabled: True
      state: started
  when: ansible_distribution == "Debian"

- block:
  - name: install chronyd configuration
    become: True
    template:
      src: etc_chrony.conf.j2
      dest: /etc/chrony.conf
      owner: root
      group: root
      mode: 0644
    notify:
      - restart chronyd

  - name: enable chronyd
    become: True
    service:
      name: chronyd.service
      enabled: True
      state: started
  when: ansible_distribution == "Fedora"

- name: configure time settings with timedatectl
  become: True
  timezone:
      name: "{{ timezone_area }}/{{ timezone }}"
      hwclock: UTC

- meta: flush_handlers

